version: '3'
services:
  adverse-events:
    container_name: adverse-events-emb  
    entrypoint: ["java", "-cp", "/target/adverse-events.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/adverse-events/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8086
    image: gsrs3/gsrs-emb-docker-adverse-events:0.0.1-SNAPSHOT
    ports:
      - 8086:8086
    volumes:
      - ../volumes/app-data:/app/data
  applications:
    container_name: applications-emb  
    entrypoint: ["java", "-cp", "/target/applications.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/applications/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8083
    image: gsrs3/gsrs-emb-docker-applications:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8083:8083
  clinical-trials:
    container_name: clinical-trials-emb
    image: gsrs3/gsrs-emb-docker-clinical-trials:0.0.1-SNAPSHOT
    entrypoint: ["java", "-cp", "/target/clinical-trials.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/clinical-trials/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8089
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8089:8089
  discovery:
    container_name: discovery-emb  
    entrypoint: ["java", "-cp", "/target/discovery.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment: 
      - SERVER_PORT=8761
    image: gsrs3/gsrs-emb-docker-discovery:0.0.1-SNAPSHOT 
    ports:
      - 8761:8761
  frontend:
    container_name: frontend-emb  
    entrypoint: ["java", "-cp", "/target/frontend.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      # Servlet context does not work from frontend-env.conf 
      - MS_SERVLET_CONTEXT_PATH_FRONTEND=/
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - MS_FRONTEND_SERVER_PORT=8082
    image: gsrs3/gsrs-emb-docker-frontend:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8082:8082
  gateway:
    container_name: gateway-emb
    entrypoint: ["java", "-cp", "/target/gateway.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    ports:
      - 9081:9081
    image: gsrs3/gsrs-emb-docker-gateway:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    environment:
      - API_BASE_PATH=/ginas/app
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - SERVER_PORT=9081
  impurities:
    container_name: impurities-emb
    entrypoint: ["java", "-cp", "/target/impurities.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/impurities/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8085
    image: gsrs3/gsrs-emb-docker-impurities:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8085:8085
  invitro-pharmacology:
    container_name: invitro-pharmacology-emb
    entrypoint: ["java", "-cp", "/target/invitro-pharmacology.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/invitro-pharmacology/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8090
    image: gsrs3/gsrs-emb-docker-invitro-pharmacology:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8090:8090
  products:
    container_name: products-emb
    entrypoint: ["java", "-cp", "/target/products.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/products/ginas.ix
      - IX_HOME_SUBSTANCES=/app/data/substances/ginas.ix
      - SERVER_PORT=8084
    image: gsrs3/gsrs-emb-docker-products:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8084:8084
  ssg4m:
    container_name: ssg4m-emb
    entrypoint: ["java", "-cp", "/target/ssg4m.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/ssg4m/ginas.ix
      - SERVER_PORT=8088
    image: gsrs3/gsrs-emb-docker-ssg4m:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    ports:
      - 8088:8088
  substances:
    container_name: substances-emb
    entrypoint: ["java", "-cp", "/target/substances.jar:classes:conf", "org.springframework.boot.loader.JarLauncher"]
    environment:
      - APPLICATION_HOST="http://gateway:9081"
      - APPLICATION_HOST_PORT=9081
      - EUREKA_SERVICE_URL="http://discovery:8761/eureka"
      - IX_HOME=/app/data/substances/ginas.ix
      - SERVER_PORT=8080
      # - JAVA_OPTS=
      #  -Dix.home=/app/data/ginas.ix
    # depends_on:
    # - discovery
    image: gsrs3/gsrs-emb-docker-substances:0.0.1-SNAPSHOT
    volumes:
      - ../volumes/app-data:/app/data
    restart: on-failure
    ports:
      - 8080:8080
  mariadb:
    container_name: mariadb-emb
    environment:
      MARIADB_ROOT_USER: root
      MARIADB_USER: root
      MARIADB_ROOT_PASSWORD: yourpassword
    image: mariadb:latest
    ports:
      - "3306:3306"
    volumes:
      - ../volumes/app-data/db/mariadb/info:/var/lib/mysql
      - ../volumes/app-data/db/mariadb/init:/docker-entrypoint-initdb.d
  #  networks:
  #    - mariadb_network
  mysql:
    container_name: mysql8-emb
    #  "--mysql-native-password=ON",
    command: ["mysqld", "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_PASSWORD: yourpassword
      MYSQL_USER: yourpassword
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    image: mysql:8.4
    ports:
      - '3306:3306'
    volumes:
      - ../volumes/app-data/db/mysql/info:/var/lib/mysql
      - ../volumes/app-data/db/mysql/init/01.sql:/docker-entrypoint-initdb.d/01.sql
#      - ../volumes/app-data/db/mysql/conf.d:/etc/mysql/conf.d
  postgresql:
    command: postgres -c 'max_connections=1000'
    container_name: postgres-emb
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=yourpassword
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ../volumes/app-data/db/postgresql/info:/var/lib/postgresql/data 
      - ../volumes/app-data/db/postgresql/init:/docker-entrypoint-initdb.d