/*
DROP DATABASE IF EXISTS adverse_events;
DROP DATABASE IF EXISTS applications;
DROP DATABASE IF EXISTS clinical_trials;
DROP DATABASE IF EXISTS impurities;
DROP DATABASE IF EXISTS invitro_pharmacology;
DROP DATABASE IF EXISTS products;
DROP DATABASE IF EXISTS ssg4m;
DROP DATABASE IF EXISTS substances;
*/
CREATE DATABASE IF NOT EXISTS adverse_events CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS applications CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS clinical_trials CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS impurities CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS invitro_pharmacology CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS products CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS ssg4m CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS substances CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

